import { useMemo } from "react";
import { X, MapPin, Printer, AlertTriangle, CheckCircle2, AlertCircle, MapPinOff } from "lucide-react";

import { Button } from "./ui/button";
import {
  generateAgronomicRecommendations,
  computeSoilHealthScore,
  getHealthScoreBand,
} from "../utils/agronomicRules";
import { formatDistance } from "../utils/geoUtils";
import { formatMetricValue } from "../constants/metrics";

const SEVERITY_STYLES = {
  high: {
    icon: AlertTriangle,
    badge: "bg-destructive/10 text-destructive border-destructive/20",
    bar: "bg-destructive",
  },
  medium: {
    icon: AlertCircle,
    badge: "bg-warning/10 text-warning border-warning/20",
    bar: "bg-warning",
  },
  good: {
    icon: CheckCircle2,
    badge: "bg-primary/10 text-primary border-primary/20",
    bar: "bg-primary",
  },
};

const SCORE_TONE_STYLES = {
  good: "text-primary bg-primary/10 border-primary/20",
  medium: "text-warning bg-warning/10 border-warning/20",
  high: "text-destructive bg-destructive/10 border-destructive/20",
  neutral: "text-muted-foreground bg-slate-100 border-border",
};

function RecommendationCard({ rec }) {
  const style = SEVERITY_STYLES[rec.severity] || SEVERITY_STYLES.good;
  const Icon = style.icon;

  return (
    <div className="relative overflow-hidden rounded-sm border border-border bg-surface pl-3">
      <span className={`absolute left-0 top-0 h-full w-1 ${style.bar}`} />
      <div className="flex items-start gap-2.5 py-3 pr-3">
        <Icon className={`mt-0.5 h-4 w-4 shrink-0 ${
          rec.severity === "high"
            ? "text-destructive"
            : rec.severity === "medium"
            ? "text-warning"
            : "text-primary"
        }`} />
        <div className="flex min-w-0 flex-col gap-1">
          <div className="flex flex-wrap items-center gap-2">
            <h4 className="text-[12px] font-semibold text-foreground">{rec.title}</h4>
            <span
              className={`inline-flex items-center rounded-sm border px-1.5 py-[1px] text-[10px] font-semibold uppercase tracking-wide ${style.badge}`}
            >
              {rec.label}: {formatMetricValue(rec.value, 2)}
            </span>
          </div>
          <p className="text-[11px] leading-relaxed text-muted-foreground">{rec.message}</p>
        </div>
      </div>
    </div>
  );
}

/**
 * RehabRecommendationModal
 * "Location Diagnostic & Rehabilitation Drawer" — a high-visibility,
 * light-styled slide-in panel triggered whenever a user drops a pin
 * or resolves their GPS location on the SpatialMap. Surfaces the
 * nearest verified soil sample (Haversine lookup), the deterministic
 * Soil Health Score, and the full agronomic prescription card set
 * generated by the rules engine. Renders as a bottom sheet on mobile
 * and a right-side drawer on desktop — strict light mode, minimum
 * 44px touch targets throughout.
 *
 * When the resolved coordinate falls outside the Kisumu County Data
 * Coverage envelope, the drawer instead renders an OUT_OF_BOUNDS
 * state: no nearest-neighbor lookup or prescription cards, just a
 * clear explanation and a "Reset Pin to Kisumu Region" action.
 */
export default function RehabRecommendationModal({
  open,
  onClose,
  coordinates,
  nearestSample,
  distanceKm,
  outOfBounds,
  onResetToKisumu,
}) {

  const recommendations = useMemo(
    () => generateAgronomicRecommendations(nearestSample),
    [nearestSample]
  );
  const healthScore = useMemo(() => computeSoilHealthScore(nearestSample), [nearestSample]);
  const scoreBand = useMemo(() => getHealthScoreBand(healthScore), [healthScore]);

  if (!open) return null;

  const handleExport = () => {
    const printWindow = window.open("", "_blank", "width=720,height=900");
    if (!printWindow) return;

    const rowsHtml = recommendations
      .map(
        (rec) => `
        <div style="border:1px solid #E2E8F0;border-left:4px solid ${
          rec.severity === "high" ? "#B91C1C" : rec.severity === "medium" ? "#B45309" : "#15803D"
        };border-radius:2px;padding:10px 14px;margin-bottom:10px;">
          <div style="font-size:13px;font-weight:600;color:#0F172A;margin-bottom:2px;">
            ${rec.title} — ${rec.label}: ${formatMetricValue(rec.value, 2)}
          </div>
          <div style="font-size:12px;color:#334155;line-height:1.5;">${rec.message}</div>
        </div>`
      )
      .join("");

    printWindow.document.write(`
      <html>
        <head>
          <title>Agronomic Advice — ${nearestSample ? nearestSample.lab_id : "Location"}</title>
          <style>
            body { font-family: Inter, Arial, sans-serif; color: #0F172A; padding: 32px; background: #F8FAFC; }
            h1 { font-size: 18px; margin-bottom: 2px; }
            h2 { font-size: 13px; color: #64748B; margin-top: 0; font-weight: 500; }
            .meta { font-size: 12px; color: #334155; margin: 4px 0 20px; }
            .score { display:inline-block; border:1px solid #E2E8F0; border-radius:2px; padding:6px 12px; font-weight:600; font-size:14px; margin-bottom:20px; }
          </style>
        </head>
        <body>
          <h1>Agronomic Rehabilitation Advice</h1>
          <h2>Digital Fertilizer Decision Support Tool — Kenya Sugar Board</h2>
          <div class="meta">
            Coordinates: ${coordinates ? `${coordinates.lat.toFixed(5)}, ${coordinates.lng.toFixed(5)}` : "—"}<br/>
            Nearest Verified Sample: ${nearestSample ? nearestSample.lab_id : "—"} (${formatDistance(distanceKm)})
          </div>
          <div class="score">Soil Health Score: ${healthScore ?? "—"} / 100 — ${scoreBand.label}</div>
          ${rowsHtml}
        </body>
      </html>
    `);
    printWindow.document.close();
    printWindow.focus();
    printWindow.print();
  };

  return (
    <>
      {/* Backdrop */}
      <div
        className="fixed inset-0 z-40 bg-slate-900/30 backdrop-blur-[1px]"
        onClick={onClose}
        aria-hidden="true"
      />

      {/* Drawer: bottom sheet on mobile, right-side panel on desktop */}
      <div
        role="dialog"
        aria-modal="true"
        className="fixed inset-x-0 bottom-0 z-50 flex max-h-[85vh] flex-col rounded-t-sm border-t border-border bg-surface shadow-card
          lg:inset-y-0 lg:right-0 lg:left-auto lg:h-full lg:max-h-full lg:w-[420px] lg:rounded-none lg:border-t-0 lg:border-l"
      >
        {/* Header */}
        <div className="flex shrink-0 items-center justify-between border-b border-border px-4 py-3.5">
          <div className="flex items-center gap-2 min-w-0">
            <div
              className={`flex h-9 w-9 shrink-0 items-center justify-center rounded-sm ${
                outOfBounds ? "bg-orange-100 text-orange-600" : "bg-primary/10 text-primary"
              }`}
            >
              {outOfBounds ? <MapPinOff className="h-4 w-4" /> : <MapPin className="h-4 w-4" />}
            </div>
            <div className="flex flex-col min-w-0">
              <h2 className="truncate text-[13px] font-semibold text-foreground">
                {outOfBounds ? "Out of Regional Data Coverage" : "Location Diagnostic & Rehabilitation"}
              </h2>
              <span className="truncate text-[11px] text-muted-foreground">
                {coordinates ? `${coordinates.lat.toFixed(5)}, ${coordinates.lng.toFixed(5)}` : "—"}
              </span>
            </div>
          </div>
          <button
            onClick={onClose}
            aria-label="Close"
            className="flex h-11 w-11 shrink-0 items-center justify-center rounded-sm text-muted-foreground transition-colors hover:bg-slate-100 hover:text-foreground"
          >
            <X className="h-4 w-4" />
          </button>
        </div>

        {/* Body */}
        {outOfBounds ? (
          <div className="flex-1 overflow-y-auto px-4 py-6">
            <div className="flex flex-col items-center gap-3 rounded-sm border border-orange-200 bg-orange-50 px-5 py-8 text-center">
              <div className="flex h-12 w-12 items-center justify-center rounded-full bg-orange-100 text-orange-600">
                <MapPinOff className="h-6 w-6" />
              </div>
              <h3 className="text-[14px] font-semibold text-foreground">Out of Regional Data Coverage</h3>
              <p className="max-w-[300px] text-[12px] leading-relaxed text-muted-foreground">
                The selected location is outside the Kisumu regional pilot area. Agronomic
                recommendations and nearest-neighbor calculations are restricted to available
                regional soil datasets.
              </p>
            </div>
          </div>
        ) : (
          <div className="flex-1 overflow-y-auto px-4 py-4">
            {/* Nearest sample + distance */}
            <div className="mb-4 flex items-center justify-between rounded-sm border border-border bg-slate-50 px-3.5 py-3">
              <div className="flex flex-col">
                <span className="text-[10px] font-semibold uppercase tracking-wide text-muted-foreground">
                  Nearest Verified Sample
                </span>
                <span className="text-[13px] font-semibold text-foreground">
                  {nearestSample ? nearestSample.lab_id : "No sample found"}
                  {nearestSample?.field_ref ? (
                    <span className="ml-1.5 font-normal text-muted-foreground">
                      ({nearestSample.field_ref})
                    </span>
                  ) : null}
                </span>
              </div>
              <span className="whitespace-nowrap rounded-sm border border-border bg-surface px-2.5 py-1 text-[11px] font-medium text-foreground">
                {formatDistance(distanceKm)}
              </span>
            </div>

            {/* Soil Health Score */}
            <div
              className={`mb-4 flex items-center justify-between rounded-sm border px-3.5 py-3 ${SCORE_TONE_STYLES[scoreBand.tone]}`}
            >
              <div className="flex flex-col">
                <span className="text-[10px] font-semibold uppercase tracking-wide opacity-80">
                  Soil Health Score
                </span>
                <span className="text-[11px] font-medium">{scoreBand.label}</span>
              </div>
              <span className="tabular text-2xl font-bold leading-none">
                {healthScore !== null ? healthScore : "—"}
                <span className="ml-1 text-xs font-normal opacity-70">/100</span>
              </span>
            </div>

            {/* Recommendation cards */}
            <div className="mb-2 flex items-center justify-between">
              <h3 className="text-[11px] font-semibold uppercase tracking-wide text-foreground">
                Agronomic Rehabilitation Recommendations
              </h3>
            </div>
            <div className="flex flex-col gap-2.5">
              {recommendations.length > 0 ? (
                recommendations.map((rec) => <RecommendationCard key={rec.id} rec={rec} />)
              ) : (
                <p className="rounded-sm border border-border bg-slate-50 px-3 py-4 text-center text-[11px] text-muted-foreground">
                  No verified sample data available for this location.
                </p>
              )}
            </div>
          </div>
        )}

        {/* Footer actions */}
        <div className="flex shrink-0 items-center gap-2 border-t border-border px-4 py-3.5">
          {outOfBounds ? (
            <Button
              variant="default"
              size="default"
              className="h-11 flex-1 min-w-0"
              onClick={onResetToKisumu}
            >
              <MapPin className="h-4 w-4" />
              Reset Pin to Kisumu Region
            </Button>
          ) : (
            <Button
              variant="outline"
              size="default"
              className="h-11 flex-1 min-w-0"
              onClick={handleExport}
            >
              <Printer className="h-4 w-4" />
              Export Agronomic Advice (PDF/Print)
            </Button>
          )}
        </div>
      </div>
    </>
  );
}


